---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
spec:
  storageClassName: longhorn-1replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi