apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: owntrack
data:
  config.alloy: |
    loki.source.file "owntracks" {
      targets = [{ __path__ = "/store/rec/user/*/*.rec", job = "owntracks" }]
      positions_path = "/tmp/positions.yaml"
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
