---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-release
  namespace: rook-ceph
spec:
  interval: 24h
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: "v1.17.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 12h
  values:
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: "v1.17.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 12h
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    cephClusterSpec:
      mon:
        count: 3
        allowMultiplePerNode: true
      mgr:
        count: 2
        allowMultiplePerNode: true
        modules:
          - name: rook
            enabled: true
      dashboard:
        enabled: true
        port: 7000
        ssl: false
      removeOSDsIfOutAndSafeToRemove: true
      storage:
        useAllNodes: true
        useAllDevices: true
      #configOverride: |
      #  [global]
      #  mon_allow_pool_delete = true
      #  osd_pool_default_size = 1
      #  osd_pool_default_min_size = 1
      resources:
        mgr:
          limits:
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        mon:
          limits:
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"

    cephBlockPools:
      - name: ceph-blockpool
        # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#spec for available configuration
        spec:
          failureDomain: host
          replicated:
            size: 1
        storageClass:
          enabled: true
          name: ceph-block

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataServer:
            activeCount: 1
            activeStandby: false
            resources:
              limits:
                cpu: "1"
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "1Gi"
          metadataPool:
            failureDomain: host
            replicated:
              size: 1
          dataPools:
            - failureDomain: host
              replicated:
                size: 1
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 1
          dataPool:
            failureDomain: host
            replicated:
              size: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              limits:
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "1Gi"
            instances: 1
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          name: ceph-bucket