---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-rancher-monitoring-alertmanager
  namespace: cattle-monitoring-system
spec:
  encryptedData:
    alertmanager.yaml: AgDBBh826BHrFtf0x3K3fzxaVMMqyphVH1c1Rvb7IQuHm/XPavySQ1Y5d1MFhzR2337lNEM3NQax5tl38w4Y+92Crul7VwIt2zYk7s6ByQMXFPoy3KtCq399sCvWc2RLczRwtmC/4qqCjCbGx1DobWTJ3uC1Mw3VasXMzXPgJHmjgOq9sdV8vs1sQnuy27/YYVNYbtS9hzsyFoI3HQn8mKcVK0s+A3M1NJcdHEXsPXfFfG0/KnCQv6OdFNYrw74NbUVMWJdUW5ujsP1/p8oe2E2L5l2IXexakzS0Kn0JxJw2ARqqNUuyY113hkvf591xpgNPkSuq3PJCCxdyDA+Em9Nf8KFt7JEak2mLEBM4VHhVNNjvCm8po1LjLPZSPD4dt8w8jztVO23mw2rPxNvK/q87ZDlrXRJoSH7O+FIq7K1BvBY3UJRGDN46h/WoYgbybZxajAswjlyrWRIhN9cPf2Y4zqcVLIfY6+G6feGu6YGS/Qo4OT42NDUu+cI2Xnd0MWurbUf5FqjIcaU3xtnk/cid8tRzJSOpoF0jSbrD40od3xLh2jEi/60CSzHGKWy71lh/Wsyy4wvjHpnCRlO8qS0rj/MBfz4JOkT1zdV+dov8Ena/NxKVfJOj2umvlxz1v/w0iYDC+J2CUhLKFIVBZRxa8IBtvoKLbHmzO4fM/izCyzD1MB86VwCxh/Lowjj2F70TxPMVmINcHEEaGyuEBANY6Y+agZ051KGlMZI9b+AvK3WdzADeylixMEj6i+s2xOfljvMPyYrLI58SUGcIPVxIKcstHA/dVG3ugKC4nBTsc+iDNwAaq9/BT7beIP1Er8yLYDskv7QY8pkPdNcFGB879PIp84osho+FJTBB0DgMuhFb4qvt3cdfcc9E3bmhv5x7EsbX88NmCBSaY0gE+k7ynDPgKjz1kmU0RXS03WXKWVTDgk1fu60ypdUUkWwqHX2Douh+c0YTG8iaM+JlZYIswq48Bglx1Uhl3AZpS6jXiKlmtJfF0TcFmvEsZo405CcRib8GbXALZTaQ8itI9KJWAkAZVkrhcUYLyffAS0Q3mKgZdVywq7l3RKFvYVjJPRf0n99+/mSZEwsyAEA/Sn6rwtc53IV6tqjmMfsCRIxdw14IEWR55M6TmmXtB1Yf8OLBOWmBbLXXFj7tgYZAnj/pyF7SGwqtg05cJvWzEOS3yUDhYi1kq0N86P4YLPCOU1mu6O3M62nCX1Q36uQ8eJYBlYr7gV+BtqxLSexDaFY5uccHVsDJfB1kJH8up5bq
  template:
    metadata:
      name: alertmanager-rancher-monitoring-alertmanager
      namespace: cattle-monitoring-system
    type: Opaque
