apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/daily-backup: enabled
  instances: 2
  storage:
    size: 10Gi
    storageClass: longhorn
