---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-ui
  namespace: flux-system
spec:
  rules:
  - host: capacitor.edge.youngandhungry.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: capacitor
            port:
              number: 9000
  tls:
  - hosts:
    - capacitor.edge.youngandhungry.org
    secretName: capacitor-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: capacitor.edge.youngandhungry.org
  dnsNames:
  - capacitor.edge.youngandhungry.org