---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  rules:
  - host: homeassistant.edge.youngandhungry.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
  tls:
  - hosts:
    - homeassistant.edge.youngandhungry.org
    secretName: nextcloud-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-tls
  namespace: homeassistant
spec:
  secretName: homeassistant-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: homeassistant.edge.youngandhungry.org
  dnsNames:
  - homeassistant.edge.youngandhungry.org
