---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
  interval: 50m
  install:
    remediation:
      retries: 3
  values: