---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blakeblackshear
  namespace: frigate
spec:
  interval: 5m
  url: https://blakeblackshear.github.io/blakeshome-charts/