---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 24h
  chart:
    spec:
      chart: velero
      version: 'latest'
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubectl:
      image:
        repository: bitnami/kubectl
        tag: latest
        pullPolicy: IfNotPresent
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.7.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    configuration:
      features: EnableCSI