---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 24h
  chart:
    spec:
      chart: velero
      version: 'latest'
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubectl:
      image:
        repository: bitnami/kubectl
        tag: latest
        pullPolicy: IfNotPresent
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    configuration:
      backupStorageLocation:
        - name: omv
          provider: aws
          bucket: velero
          default: true
          config:
            region: us-east-1
            s3Url: https://192.168.180.19:9000
            insecureSkipTLSVerify: true
            s3ForcePathStyle: true
          credential:
            name: minio-s3-credentials
            key: cloud
      volumeSnapshotLocation:
        - name: omv
          provider: aws
          config:
            region: us-east-1
            s3Url: https://192.168.180.19:9000
            insecureSkipTLSVerify: true
            s3ForcePathStyle: true