apiVersion: v1
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gemlLM1ZwOGF6cW9wajVuZWVuZmgKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gWHRZSHpMOE9rc01QWFd2aEpobXZCV3RPVUhYUkgyQkFIamRVbWNTUw==
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-s3-credentials
  namespace: velero