apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama
  namespace: ai
spec:
  interval: 24h
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ai
spec:
  interval: 2h
  chart:
    spec:
      chart: ollama
      version: 1.68.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ai
      interval: 2h
  values:
    ollama:
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      models:
        pull:
          - llama3
    nodeSelector:
      kubernetes.io/hostname: k3s03
    persistence:
      enabled: true
      size: 15Gi
      storageClass: longhorn
