apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 30Gi
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud 
      secret:
        name: nextcloud-db-secret
#  externalClusters:
#    - name: nextcloud-db-external
#      connection:
#        host: nextcloud-db.nextcloud.svc.cluster.local
#        port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
data:
  username: bmV4dGNsb3Vk
  password: bXlTZWNyZXRQYXNzd29yZA==