apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nextcloud
  - s3.yaml
  - db.yaml
  #- velero.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease