apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      version: "6.0.0"
  values:
    nextcloud:
      host: cloud.edge.youngandhungry.org
      username: admin
      password: changeme
      ## Use an existing secret
      existingSecret:
        enabled: false
        # secretName: nameofsecret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        tokenKey: ""
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      trusted_domains:
        - cloud.edge.youngandhungry.org
      objectStore:
        s3:
          enabled: true
          #accessKey: "RS4D0ZGTXWZVKPFCPE1Ek"
          #secretKey: "FsNrdQTmq8ClwfU0WioUeFzobOghDe6nJRuSXkiLk"
          legacyAuth: false
          host: "rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local"
          ssl: false
          port: "80"
          region: "eu-west-1"
          bucket: "ceph-bkt"
          #prefix: "your-prefix"
          usePathStyle: true
          #autoCreate: false
          #storageClass: "STANDARD"
          #sse_c_key: "your-sse-c-key"
          existingSecret: "ceph-bucket"
          secretKeys:
          #  host: "your-secret-key-host"
            accessKey: "AWS_ACCESS_KEY_ID"
            secretKey: "AWS_SECRET_ACCESS_KEY"
          #  bucket: "your-secret-key-bucket"
          #  sse_c_key: "your-secret-key-sse_c_key"

    internalDatabase:
      enabled: false
      name: nextcloud

    externalDatabase:
      enabled: true
      type: postgresql
      host: "nextcloud-db-rw.nextcloud.svc.cluster.local"
      user: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        usernameKey: username
        passwordKey: password
        # hostKey: db-hostname-or-ip
        # databaseKey: db-name


    postgresql:
      enabled: false
      global:
        postgresql:
          auth:
            username: nextcloud
            password: changeme
            database: nextcloud
      primary:
        persistence:
          enabled: true

    persistence:
      # Nextcloud Data (/var/www/html)
      enabled: true
      annotations: {}
      accessMode: ReadWriteOnce
      size: 8Gi
      ## Use an additional pvc for the data directory rather than a subpath of the default PVC
      ## Useful to store data on a different storageClass (e.g. on slower disks)
      nextcloudData:
        enabled: false
        subPath:
        annotations: {}
        # storageClass: "-"
        # existingClaim:
        accessMode: ReadWriteOnce
        size: 10Gi

    redis:
      enabled: true
      auth:
        enabled: true
        password: 'changeme'
        # name of an existing secret with Redis® credentials (instead of auth.password), must be created ahead of time
        existingSecret: ""
        # Password key to be retrieved from existing secret
        existingSecretPasswordKey: ""
      # Since Redis is used for caching only, you might want to use a storageClass with different reclaim policy and backup settings
      global:
        storageClass: ""
      master:
        persistence:
          enabled: true
      replica:
        persistence:
          enabled: true

    imaginary:
      enabled: true

    metrics:
      enabled: true