apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    nextcloud:
      trusted_domains:
        - cloud.edge.youngandhungry.org

