apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: nextcloud-daily
  namespace: velero
spec:
  schedule: "0 12 * * *" # täglich um 12:00 Uhr
  template:
    includedNamespaces:
      - nextcloud
    snapshotVolumes: true
    ttl: 2232h # 3 Monate Aufbewahrung