apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: omv
  namespace: velero
  labels:
    velero.io/storage-location: default
spec:
  provider: aws
  default: true
  objectStorage:
    bucket: velero
  config:
    region: us-east-1
    s3Url: https://192.168.180.19:9000
    insecureSkipTLSVerify: "true"
    s3ForcePathStyle: "true"
  credential:
    name: minio-s3-credentials
    key: cloud
