---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: velero
    meta.helm.sh/release-namespace: velero
spec:
  backupSyncPeriod: 10m0s
  provider: aws
  objectStorage:
    bucket: velero
  #credential:
  #  name: hetzner-s3-credentials
  #  key: cloud
  config:
    region: eu-central-1
    s3ForcePathStyle: "true"
    #s3Url: https://omv.youngandhungry.org:9000
