---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freellmapi-secret
  namespace: freellmapi
spec:
  encryptedData:
    ENCRYPTION_KEY: AgArZWxeXRO9OmYRh/EaJ/H2jO6KcXmePfUmds4ffPKK4nP1J90OAsdrvV6XnOiceHr5RLB+xTy3DnuB6cRvLhaC1dZmfYPflqqV4sEBDwDxYsuo1mpcN0xC9M+/Yg+5iVxG7xlxG3OV9vOrtgQP9KAKUbkTLJ+gnsZyIyFipiAXhH22n1TvuhC4VBj4b8usXuNXWW2Ozx2LiOlC2J5NWZohvmXizj6kAKtwrAOluvWYcG7aQB+0wM8UqZ+mLoTSDgCw2rhBdBhN882Hwo2GJAA9SNVxxIf7bDUBcwioAZVUXAOVrRCdaLjAf0R/VL57hm5Uq5KgngipvdwEF9k0dxuFQcwn+/dyF3EX82qTFT4ZTb6QCyo4wJXZ3UA3uvsRoy2ZFHgPowAyQSwbGupNpqDfEHNCUbE+z32tJkJWvNUdbkv9WbBJPZqaN9Iaz0fxkg3YwxDfma2MF+K6a2mV5VygBGND1DFjjagISnaOnD75sxrNZwTMkg8tFzghIoR47yDBA9k7DyVi4aP3FbH69sc83RivgNcpLxbWvwj9EIWic0gmRhDmw86SmcDFGT/sXZHGAWcgwIAgEdckPaL0IMk+kqezBsBbyj5qC5S8HbJYw9Eh+Zfjio9Y3Q3RO4+6vhISmYlm6Xg5sW0ZdjyieqnL1Vj/Fikq7fQRoQbeBDmwSpNSK6VOiXeS+yp1LsJazCKjdGVo2owhiI4/roo9/OI4k5jZvMoyJrUBiQRDmCZ5rg==
  template:
    metadata:
      name: freellmapi-secret
      namespace: freellmapi
    type: Opaque
