---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: cert-manager-edge@youngandhungry.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - dns01:
          webhook:
            groupName: acme.edge.youngandhungry.org
            solverName: hetzner
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: api-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: cert-manager-edge@youngandhungry.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-nginx
    solvers:
      - dns01:
          webhook:
            groupName: acme.edge.youngandhungry.org
            solverName: hetzner
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: api-key
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCM6AGAyrCvUzpnKXAzgdxol7DavaQPOghf8PothWSKgjOEGltf17dCfNs/bo5csmAA8fg5THR94k9eVGMkpj7u/Aw/J0oJtuvXeNCx7OT6jYjh3wu8Ioo8UYiR1Ejm0Z6100h6E5evb9femFPf7eaDY2qEr9t1spbcL3QIcWGuDxqsWNd7x2MaStM/LZsEqumh9oHZCksxld1oGj0qasitgox+SaiLmMKDvZv6fzVRe9zyZmEfghDQk9LTpHXKJY2bk943Lm1RYEfAiWgsO6YSDTb379zx6xse05ehlOC9+1ov8SkaTTrn6i8xl/Qq8g/vLbboz6D8gByM0PlmUXVh4acOhSpnCWXQgblZgyhzyUi7tIDRiiPaVUZpuccjEpjeV0WkstE0vlb2L2n9h1fd3acg9ooiMOvNW0DTZsspxMqM6wfNecqoiKmE5o+PxLrI9NiVpG6EWxWnrjx9Yu0FGMGBsAD78UqXpwMwJ1Yzep4FVm6C8oOGNyROtMCjca/A89+bXZhLQPwTi3fYeguq8y4nuMiOQEAogAFjgAQwWlM3GsTX7PLyd9N7IerBOlmfq+vblL9VqeacezfIfDxbtUX/BZNbJUnZqQTmz04NZE3J6C34nNTSMibw1zCn5nvrkoZGZhA9qXpV1JKwoQ3bhULcTGuegeyvuWvWdBOUebOvpuR0RxIhLO5+i+khTPqpbAdM5S9+Lrtv6rttGCL4gFPPwdgfMYI8rlwoK7VdJZL7vlwo5+LlNsQ5srecjpSnSo4cylAZunyjFaWfsRtp
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager