apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring-crd
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  chart:
    spec:
      chart: ./charts/rancher-monitoring-crd/105.0.0+up57.0.3 # 102.0.0+up40.1.2 works
      version: '105.0.0+up57.0.3'
      sourceRef:
        kind: GitRepository
        name: rancher-charts
        namespace: flux-system
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3