apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  chart:
    spec:
      chart: ./charts/rancher-monitoring/105.0.0+up57.0.3 # 102.0.0+up40.1.2 works
      version: '105.0.0+up57.0.3' # 102.0.0+up40.1.2 works
      sourceRef:
        kind: GitRepository
        name: rancher-charts
        namespace: flux-system
      interval: 24h
  values:
    grafana:
      enabled: true
      grafana.ini:
        auth.anonymous:
          enabled: false
        auth.basic:
          enabled: true
      adminUser: null
      adminPassword: null
      admin:
        existingSecret: "rancher-monitoring-grafana"
        userKey: admin-user
        passwordKey: admin-password
      #persistence:
      #  enabled: true
      #  storageClassName: longhorn
      #  size: 2Gi
      #  accessModes:
      #    - ReadWriteOnce
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Loki
              type: loki
              url: http://loki.logging.svc.cluster.local:3100
              jsonData:
                maxLines: 1000
            - name: Alertmanager
              type: alertmanager
              url: http://alertmanager-operated.cattle-monitoring-system.svc.cluster.local:9093
              jsonData:
                implementation: prometheus
    prometheus:
      enabled: true
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true       
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi
        thanos:
          objectStorageConfig:
            existingSecret:
              name: "thanos-objstore-config"
              key: "thanos.yaml"
    #thanosRuler:
    #  enabled: true
    #  serviceMonitor:
    #    selfMonitor: true
    #  thanosRulerSpec:
    #    retention: 168h # 7d
    #    objectStorageConfig:
    #      existingSecret:
    #        name: "thanos-objstore-config"
    #        key: "thanos.yaml"
    #    queryEndpoints:
    #      - http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090/
    rke2ControllerManager:
      enabled: true
    rke2Scheduler:
      enabled: true
    rke2Proxy:
      enabled: true
    rke2Etcd:
      enabled: true
    rke2IngressNginx:
      enabled: true
    alertmanager:
      enabled: true
      alertmanagerSpec: 
        configSecret: alertmanager-main
